// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxyPlBN_0ZlW-p8bdTKu0gX-D9kO12RYI',
    appId: '1:316474289696:web:9fba6d048779f97517d645',
    messagingSenderId: '316474289696',
    projectId: 'filmmend-me',
    authDomain: 'filmmend-me.firebaseapp.com',
    storageBucket: 'filmmend-me.firebasestorage.app',
    measurementId: 'G-9QRF1E4RL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBslJQWAwcLMB7xFoZ2hY1ZljhGW2wAV90',
    appId: '1:316474289696:android:f2c63fc5fd57f23217d645',
    messagingSenderId: '316474289696',
    projectId: 'filmmend-me',
    storageBucket: 'filmmend-me.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk7WqHbcxpsFiYeivWrGlb_cUSCmwy1KM',
    appId: '1:316474289696:ios:0540e86cc2fc42cf17d645',
    messagingSenderId: '316474289696',
    projectId: 'filmmend-me',
    storageBucket: 'filmmend-me.firebasestorage.app',
    iosBundleId: 'com.example.filmmendMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk7WqHbcxpsFiYeivWrGlb_cUSCmwy1KM',
    appId: '1:316474289696:ios:0540e86cc2fc42cf17d645',
    messagingSenderId: '316474289696',
    projectId: 'filmmend-me',
    storageBucket: 'filmmend-me.firebasestorage.app',
    iosBundleId: 'com.example.filmmendMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxyPlBN_0ZlW-p8bdTKu0gX-D9kO12RYI',
    appId: '1:316474289696:web:fb362ce3a153dabf17d645',
    messagingSenderId: '316474289696',
    projectId: 'filmmend-me',
    authDomain: 'filmmend-me.firebaseapp.com',
    storageBucket: 'filmmend-me.firebasestorage.app',
    measurementId: 'G-ZGYSRP0FMB',
  );
}
